#release configuration
#Sat May 09 18:37:39 EDT 2026
completedPhase=check-poms
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.scm.net.snytkine.springboot\:spring-boot-starter-easy-rest-clients.connection=scm\:git\:https\://github.com/snytkine/spring-boot-starter-easy-rest-clients.git
project.scm.net.snytkine.springboot\:spring-boot-starter-easy-rest-clients.developerConnection=scm\:git\:https\://github.com/snytkine/spring-boot-starter-easy-rest-clients.git
project.scm.net.snytkine.springboot\:spring-boot-starter-easy-rest-clients.tag=HEAD
project.scm.net.snytkine.springboot\:spring-boot-starter-easy-rest-clients.url=https\://github.com/snytkine/spring-boot-starter-easy-rest-clients
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=true
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:https\://github.com/snytkine/spring-boot-starter-easy-rest-clients.git
